### ISSUE TITLE
Frontend code refactor

### ISSUE THREAD

**Issue by jonahdlin** [PathwayCommons/app-ui#101]
Small style and best practice tasks that need to be done across the frontend.

- [ ] Receive URI from props, not window
- [x] #140 Use arrow functions to resolve `this.method = this.method.bind(this)`
- [ ] Receive all metadata in View from `graphJSON`, **none** from PC2
- [ ] Use `fit()` and `minzoom` and `maxzoom` properties to change the fit of graphs on the screen
- [ ] Use custom React tooltip component instead of tippy.js (depends on #102)
- [x] #140 Clean up the `updateIfOutOfMenu` function.
  - [x] #140 The event listener should be activated on component mount, and should be removed only when the component unmounts
  - [x] #140 The check for open and locked should be done within `updateIfOutOfMenu`
  - [x] #140 Instead of the loop, use `querySelector` to get the root of the sidebar and then do an equality check to tell if the click occurred in the sidebar or not
- [x] #140 Tool button styling should be done in CSS and toggled within React by state and class changes
- [x] #140 Any variables in any state that don't ever change should be created as `const` outside the component
- [x] #108 Give CSS colour variables more semantic names
