### ISSUE TITLE
Paint - Use server metadata/layouts

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#122]
Painted graph still has the issues of non-painted graphs in that humans still can't understand them.  Use the layout and metadata api, see if the painted graph is any more readable.

**Comment by jvwong** [comment]
Can you clarify  - are you saying layouts bad?

**Comment by d2fong** [comment]
No I am saying that I just get un-augmented sbgn from pc itself, when I should be getting the cyjson with metadata from our server.

**Comment by d2fong** [comment]
## TODO

- [ ] Refactor cy module in /view to belong to /common
- [ ] Move tooltip generation out from /view
- [ ] Allow event configuration via options args
- [ ] Change /view to be a consumer of the cy module
- [ ] Change paint to be a consumer of the CDC service

**Comment by d2fong** [comment]
Pushed back to near the winter break.
